### ISSUE TITLE
document.hpp not parse AudioPackFormatHoa

### ISSUE THREAD

**Issue by xiaokuer** [ebu/libadm#174]
I want to create a HOA-based ADM XML file, but document.hpp doesn't contain AudioPackFormatHoa, so the audioPackFormat element is missing from the xml file. I'm gon na need your help
[sine_sweep_order3_SN3D.txt](https://github.com/ebu/libadm/files/10225735/sine_sweep_order3_SN3D.txt)

**Comment by rsjbailey** [comment]
Hi, the attached .txt file has a reference to pack format `AP_00040001`. This is a common definition for SN3D-Order1-3D, so is not included in the output XML. (Common definitions are a set of commonly used packs/channels that an ADM implementation should provide, rather than you having to specify them explicitly in every file that makes use of them)

**Comment by xiaokuer** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
